gcp:
  project_name: "CustomerSentimentAnalysis"
  project_id: "fluid-dreamer-423211-s9"
  credentials_path: "./credentials.json"
  region_name: "us-central1" 

model:
  model_name: text-bison@001
  preprocessing:
      data_path: ./model/data/Reviews.csv
  postprocessing:
    output_path: ./model/data/final_predictions.csv