gcp:
  project_name: "CustomerSentimentAnalysis"
  project_id: "fluid-dreamer-423211-s9"
  credentials_path: "./credentials.json"
  region_name: "us-central1"
  

model:
  model_name: text-bison@001
  preprocessing:
      data_path: Reviews.csv
  postprocessing:
    output_path: final_predictions.csv
  output_bucket:
    bucket_name: csa_model_output
    bucket_output_path: output/final_predictions.csv
  input_bucket:
    bucket_name: csa_model_input
    bucket_input_path: Reviews.csv
  